### ISSUE TITLE
Importing from PkHex is missing some encounters

### ISSUE THREAD

**Issue by AarCon** [TeamLumi/LumiPlat_NuzlockeTracker#25]
**Describe the bug**

Some Encounters aren't imported via the Import By Table from PkHex, namely:
 - Starter
 - Jubilife City

**To Reproduce**

1. Go to the Import page
2. Select the "Import game by table [Beta]" option
3. Open [PkLumiHex](https://github.com/TalonSabre/PKLumiHex) with a save that has the desired encounters.
4. Follow the instructions [here](https://github.com/diballesteros/nuzlocke/wiki/How-to-generate-table-with-PkHeX) to generate the info for the import.
5. Paste the table output from PkLumiHex into the input section and click "Apply"
6. Notice the Encounters listed above don't auto populate.

**Expected behavior**

All Encounters should be filled out correctly if the save has been following Nuzlocke rules strictly.

**Comment by IRSBountyhunter** [comment]
https://file.io/ZydDEbg3qbAi

**Comment by AarCon** [comment]
Worked on this and it should be closed with 73fd003e2c185737d6ee8f31d3f07d6d70b4b260
